export const FETCH_SELF = 'fetch_self'

export const ADD_ERROR = 'add_error'
export const ADD_MESSAGE = 'add_message'
export const REMOVE_MESSAGE = 'remove_message'

export const FETCH_MODULES = 'fetch_modules'
export const FETCH_MODULE = 'fetch_module'
export const ADD_MODULE = 'add_module'
export const REMOVE_MODULE = 'remove_module'

export const FETCH_LESSONS = 'fetch_lessons'
export const FETCH_LESSON = 'fetch_lesson'
export const ADD_LESSON = 'add_lesson'
export const REMOVE_LESSON = 'remove_lesson'
export const UPDATE_LESSON = 'update_lesson'

export const FETCH_PROJECTS = 'fetch_projects'
export const FETCH_PROJECT = 'fetch_project'
export const ADD_PROJECT = 'add_project'
export const REMOVE_LESSON_IN_CHAPTER = 'remove_lesson_in_chapter'
export const UPDATE_LESSON_IN_CHAPTER = 'update_lesson_in_chapter'
export const REMOVE_PROJECT = 'remove_project'

export const FETCH_SCHOOLS = 'fetch_schools'
export const FETCH_SCHOOLS_LIST = 'fetch_schools_list'
export const FETCH_SCHOOL = 'fetch_school'
export const ADD_SCHOOL = 'add_school'
export const REMOVE_SCHOOL = 'remove_school'

export const FETCH_COMPILER_LIST = 'get_compiler_list'

export const FETCH_SKILLS = 'fetch_skills'
export const FETCH_SKILL = 'fetch_skill'
export const ADD_SKILL = 'add_skill'
export const REMOVE_SKILL = 'remove_skill'

export const FETCH_USERS = 'fetch_users'
export const FETCH_USER = 'fetch_user'
export const FETCH_SCHOOL_ADMINS = 'fetch_school_admins'
export const ADD_USER = 'add_user'
export const REMOVE_USER = 'remove_user'

export const FETCH_SUBMISSIONS = 'fetch_submissions'
export const FETCH_SUBMISSION = 'fetch_submission'
export const REMOVE_SUBMISSION = 'remove_submission'

export const FETCH_CATEGORIES = 'fetch_categories'
export const FETCH_CATEGORY = 'fetch_category'
export const ADD_CATEGORY = 'add_category'
export const REMOVE_CATEGORY = 'remove_category'
export const UPDATE_CATEGORY = 'update_category'

export const FETCH_GLOBAL_HINTS = 'fetch_hints'
export const FETCH_GLOBAL_HINT = 'fetch_hint'
export const ADD_GLOBAL_HINT = 'add_hint'
export const REMOVE_GLOBAL_HINT = 'remove_hint'
export const UPDATE_GLOBAL_HINT = 'update_hint'

export const FETCH_NCOURSES = 'fetch_ncourses'
export const FETCH_NCOURSE = 'fetch_ncourse'
export const ADD_NCOURSE = 'add_ncourse'
export const UPDATE_NCOURSE = 'update_ncourse'
export const REMOVE_NCOURSE = 'remove_ncourse'

export const FETCH_NLESSONS = 'fetch_nlessons'
export const FETCH_NLESSON = 'fetch_nlesson'
export const ADD_NLESSON = 'add_nlesson'
export const UPDATE_NLESSON = 'update_nlesson'
export const REMOVE_NLESSON = 'remove_nlesson'

export const FETCH_NACTIVITIES = 'fetch_nactivities'
export const FETCH_NACTIVITY = 'fetch_nactivity'
export const ADD_NACTIVITY = 'add_nactivity'
export const UPDATE_NACTIVITY = 'update_nactivity'
export const REMOVE_NACTIVITY = 'remove_nactivity'

export const FETCH_NQUESTIONS = 'fetch_nquestions'
export const FETCH_NQUESTION = 'fetch_nquestion'
export const ADD_NQUESTION = 'add_nquetion'
export const UPDATE_NQUESTION = 'update_nquestion'
export const REMOVE_NQUESTION = 'remove_nquestion'
