export const FETCH_USERS = 'fetch_users'
export const FETCH_USER = 'fetch_user'
export const FETCH_SCHOOL_ADMINS = 'fetch_school_admins'
export const ADD_USER = 'add_user'
export const REMOVE_USER = 'remove_user'
export const ADD_ERROR = 'add_error'
export const ADD_MESSAGE = 'add_message'
export const REMOVE_MESSAGE = 'remove_message'
